### PR TITLE
Refactored API for better abstraction and general purpose

### PR DESCRIPTION
**Pull request by seanrichardson95**
1. Moved all querying logic from _flagsController.js_ to methods on an instance of `PGTable` (renamed from "Pg")
2. Initialized an instance of `PGTable` in _flagsController.js_ which is passed objects (or nothing if nothing required) that are gotten from `req.body`. This transformation logic still lives in _flagsController.js_, although it's been tweaked.
3. The `getNowString()` function that's used to create a string of the current time has been moved to a _utils.js_ file which'll house all miscellaneous utility functions.

Notes on the `PGTable` class:
- It's general purpose, so we should be able to use it for any table.
- It takes two arguments when initialized, the name of the table, and the fields (columns) of that table. This two arguments are saved as state and used to form querystrings.

Future work:
- Better validation and error handling

### CODE REVIEW

**Review by calebrs — COMMENTED** [review]
This looks pretty good, but here are some things to consider with this implemented to work with any table:

- As it stands now, you'd be able to expose any of your tables to CRUD operations, which you may not want. For example, you may not want someone using this API to have the ability to delete rows from the `apps` table.
- Not all table operations will be implemented the same. Each table might have unique CRUD operations. For example, you might want to run a more specific query on the data instead of returning a whole row. We might want to implement a `toggleFlag` function on the `flags` table that only updates the status, which may be more performant than iterating through all attributes each time you update. Essentially, you lose some flexibility in how you query the database.

Also, is there a way to get around having to hard code the fields/attributes? I only wonder because you'd have to update them every time the schema changes. Could we get that from the request, maybe?

**Comment by seanrichardson95** [comment]
@calebrs I understand your concern, but I think giving people the option to expose their tables to the API is fine. I figure if someone wants to be able to delete rows from their `apps` table, why not let them? We don't have to add the API endpoints for the CRUD actions we don't want to provide, but if someone wants to edit our code to create them, why not make it as easy as possible?

In terms of the unique CRUD operations, I figured that we could just have the unique stuff within the controllers, for example,  `createUpdateFlagObj` in _flagsControllers.js_. Also, I don't think performance will be an issue since our tables won't have many columns, and iterating through an array of < 10 values is very very fast.

In terms of the hardcoding fields/attributes I was struggling to think of a way to not hard code it since you can't put requests in the constructor, but after reviewing Julia's most recent commits to the SDK, I'm thinking I can just add an `init()` method which queries the DB for the column names and adds it to the state.

**Comment by calebrs** [comment]
For the 'deleting an app row', if a user deleted a row from 'apps' it will effectively orphan any flags attached to it. There's no guarantees about how the database is implemented, so the corresponding flags may not be deleted.

So you're thinking we split queries into two different places? Specific functions would be separate from the more general ones?

This may work for our purposes, but out of the REST APIs I've seen, it seems like they implement specific queries over each table.

**Comment by julia-martin** [comment]
@calebrs Question about "There's no guarantees about how the database is implemented" -- doesn't our SQL file dictate exactly how the database is implemented? That there will be an `apps` table and a `flags` table connected by `app_id`? And isn't it the intention that when deleting an app, all its flags/other data should also be deleted?

**Comment by calebrs** [comment]
@julia-martin Yes, you're right. Not a great example. I guess the point I'm trying to illustrate is that we're giving up control of how we expect the db to be queried.

**Comment by seanrichardson95** [comment]
There may be a tradeoff there, but I think it's worth it since it'll make future controllers that query different tables to be much easier to implement.

**Pull request merged**
