### PR TITLE
Create an experiment from a feature flag from the UI

### PR DESCRIPTION
**Pull request by julia-martin**
# Routing
Added BrowserRouter and Routes since we now have two kinds of pages (the main dashboard and individual flag pages). You can click on the first item in the left nav to get back to the dashboard.

# Individual Flag Page
If its `is_experiment` field is `false`, then it will show a "Create Experiment" button. Clicking the button will send a PUT request to the API to turn that field to `true`.
If the `is_experiment` field is `true`, then it will show the experiment details (will contain the viz and stats), and a "Stop Experiment" button (also sends a PUT request).

### CODE REVIEW

**Comment by seanrichardson95** [comment]
For the sorting, maybe we should do it by `id` instead of by `date_created`? As of right now when I toggle a flag it messes up the order of the flags. Maybe this is only an issue with the dummy data since the date-created at the same time and in real life it wouldn't be like that, but still I think we should be able to have a consistent sort between two flags that are created at the same time.

**Comment by seanrichardson95** [comment]
Found a bug: When I'm on the flag page, like `/flags/2` and I refresh, the page is blank. If you'd like to solve this with a new GET request to the backend, lmk and I can implement that for you. If you choose some other way, that's cool as well.

**Comment by julia-martin** [comment]
Yeah that's fine, I originally had it sorted by `id` and decided to change it to `date_created`, but we can do `id` for now to make things work better.

Oh yeah, I couldn't decide whether to fix that now or not. The user is supposed to start from the main dashboard and then go to the flag page and that will always work. Should I go ahead and fix it now?

**Comment by seanrichardson95** [comment]
The sorting looks great now.

I think we should have it done before we consider our MVP done. If you put it off for now I just suggest adding a todo for it (or add it to an existing todo).

Otherwise, it looks great!

**Review by seanrichardson95 — APPROVED** [review]

**Comment by julia-martin** [comment]
I'm working on implementing the fix, but it'll require a new function to be added to `PGTable` to query for one row for a single flag given the id. Do you want to do that or do you want me to?

**Comment by julia-martin** [comment]
@seanrichardson95 I put in some temporary logic in the `flagsController` file where i'm just filtering after `getAllRows`, but it'd be better to have a different query at some point that only queries for the one flag by `id` .

**Comment by seanrichardson95** [comment]
Looks good! Something I noticed while refreshing the single flag page is that it ends up querying the database twice. Not a big deal, but it might be something we want to look into later.

**Comment by calebrs** [comment]
Cool, looks good to me. It clears up some of the questions I had about the front end.

As for the route, it doesn't seem very efficient to get all the flags from the db, just to filter it out for the one you need with JavaScript. Wouldn't be better to create a new SQL query that grabs the exact flag that you need?

**Comment by julia-martin** [comment]
@calebrs yeah exactly, we were discussing that in the earlier comments

**Pull request merged**
