### PR TITLE
Frontend skeleton

### PR DESCRIPTION
**Pull request by julia-martin**
- Created components and UI, user is able to do CRUD operations from a frontend perspective

### CODE REVIEW

**Comment by julia-martin** [comment]
All the frontend features work, just waiting for the API endpoints to be implemented so I can test the API calls (currently just using dummy data) in `ApiClient.js`

**Comment by julia-martin** [comment]
Screenshots:
main page
modal

**Comment by seanrichardson95** [comment]
Overall, looks good. There's just a small bug where when I create a new flag, the UI doesn't show the new flag I created until I refresh the page.

**Comment by calebrs** [comment]
Looks good to me! Great job!

**Comment by seanrichardson95** [comment]
Looks good to me too, great work Julia! Going to merge now.

**Pull request merged**
