### PR TITLE
Miscellaneous CSS improvements

### PR DESCRIPTION
**Pull request by julia-martin**
Made some fixes to the CSS:
- Fixed overlay so that it covers the whole screen (earlier it only covered the top 90% or so)
- Changed the X icon in the "New Flag" modal to a better-looking one
- Made most of the forms look better - more aligned and more padding
- Small changes to the metric checkbox buttons and added shadow
- In the experiment info component, conditionally show the Name and Description fields only if it has them

### CODE REVIEW

**Comment by seanrichardson95** [comment]
Is it possible to get this on one line? Or two with a more natural split? 
image

**Comment by seanrichardson95** [comment]
Do you think this would look better if everything was centered?
image

**Comment by seanrichardson95** [comment]
Overall this looks really good. I like the new looks of the metric buttons especially. Maybe just some tweaks that I mentioned above. Looking forward to the next iteration.

**Comment by julia-martin** [comment]
Sure, made the form wider so that it can fit on one line when you have your screen big enough:
new flag

And I centered the select metrics and buttons on the Create Experiment form:
create expt

**Comment by seanrichardson95** [comment]
Great work Julia!

**Review by seanrichardson95 — APPROVED** [review]

**Pull request merged**
