### PR TITLE
Frontend refactoring

### PR DESCRIPTION
**Pull request by julia-martin**
- Changed the text/border color of the DB connection button to turquoise on hover
- Moved form components into a `forms` folder and updated path names
- Extracted the interval bar chart out of `MetricResultRow` into its own component

### CODE REVIEW

**Comment by seanrichardson95** [comment]
New changes look good! Maybe put `ExperimentInfo`, `ExperimentResults`, `ExposuresChart` and `IntervalChart` into its own folder? Called something like "experiments" or "experimentsDisplay" or something

**Comment by seanrichardson95** [comment]
Could we make the shadow a little darker? Or just tweak something about it to make it clearer what parts of this page are grouped together? They kind of blend together at the moment
image

**Comment by julia-martin** [comment]
Yeah! Good ideas. I made some edits, let me know what you think:
New

**Comment by seanrichardson95** [comment]
new file structure looks great. I like that the separation is more clear, but I'm not sure about the color of the experiment information. 
image
I think I prefer it without that style of box. Like no 3D on that, like how we used to have it before. Sorry if that's annoying.

However I like the shadow on the div that surrounds the entire experiment. This (below) looks really good. 
I don't know if I'd want that applied to the experiment details (id, duration, etc.) but I definitely want it to stay on the entire experiment div.
image

**Comment by julia-martin** [comment]
Just to confirm do you mean you prefer it with no box like this?
flat

**Comment by seanrichardson95** [comment]
> Just to confirm do you mean you prefer it with no box like this?

Maybe we could have a divider line between the experiment details and the charts? Like how they can do on Notion. But maybe thin, black, and with a small shadow on the bottom. 
image

**Pull request merged**
