### PR TITLE
Visualization of experiment results

### PR DESCRIPTION
**Pull request by julia-martin**
- Added line chart of exposures data (if there are no exposures, it says "No exposure data yet". 
- Added a table summary of the statistics for each metric on the experiment
- Similarly if there are no statistics data, it prompts the user to click the "Refresh results" button if they have enough sample size.
- The numbers are formatted according to the metrics' type (binomial returns a percentage, revenue adds a dollar sign) and rounded to 2 decimal places (I just thought that was a good amount of precision for most cases).
- In the p-value column, it will say "Significant" in green if it is below the alpha threshold (0.05).
- In the last column there is a chart showing the 95% confidence interval, and 0 is marked with a purple line. It's not as fancy as other tools, but I couldn't find a better way without using a paid product.
- You can hover over the charts to see the numbers for each data point
- I also restyled the portion at the top of the Experiment Info showing the duration, description, etc.

Example of a newly created experiment with no data yet:

Newly created

Example of an experiment that has some data:

expt_1

# Future work
- Will definitely add some explanations about best practices, and how to interpret each number. I'm not sure whether to put that right on the UI or just in the documentation. It's something they should only need to read once, not every time they see it, so I'm thinking about putting it mostly in documentation or an "FAQ" page?
- Thinking about adding the current sample size for each group somewhere. Not sure if that's necessary though since there's already the chart showing that.

### CODE REVIEW

**Comment by seanrichardson95** [comment]
I edited an experiment to add a metric and it broke the UI. Not sure why this is happening, going to investigate further.

After I removed the row in the `experiment_metrics` table for the second metric, the page started working again.

**Comment by seanrichardson95** [comment]
I found another bug. Even though my "test" and "control" exposures were updated up until 2022-03-19, the "test" sample size data stops showing up after 03-14 
image
image

**Comment by julia-martin** [comment]
I fixed the first bug (I needed to check for null values before rendering), but I'm not getting the same issue with the chart. Are you using the seed data I sent or your own?

**Comment by seanrichardson95** [comment]
> I fixed the first bug (I needed to check for null values before rendering), but I'm not getting the same issue with the chart. Are you using the seed data I sent or your own?

My own. I didn't see the seed data until now.

**Comment by julia-martin** [comment]
I'm assuming your exposures for the test group had a later start date which is what caused the line to start on the wrong day? To me that sounds like a small edge case that shouldn't happen in real life since users have a 50/50 chance of being in each group

**Comment by seanrichardson95** [comment]
> I'm assuming your exposures for the test group had a later start date which is what caused the line to start on the wrong day? To me that sounds like a small edge case that shouldn't happen in real life since users have a 50/50 chance of being in each group

Now that I'm using your seed data, that issue has disappeared.

Also, good job on that bug fix!

**Comment by seanrichardson95** [comment]
I hit "refresh results" and while it sent a PUT request, the new results weren't showing up until I refreshed the page.

**Comment by seanrichardson95** [comment]
> I hit "refresh results" and while it sent a PUT request, the new results weren't showing up until I refreshed the page.

Also, some sort of confirmation that I sent the request (maybe a loading symbol) would be cool. But maybe that's more of a refactoring that we can save for a future pull request

**Comment by seanrichardson95** [comment]
I edited the experiment, removing the "Signup" metric, and the name for "Time on Site" disappeared. The same thing happened when I did it the other way too (had both metrics, removed Time on Site, couldn't see "Signup")
image

UPDATE: I just changed the name of the experiment (left both metrics untouched) and the same issue happens. I'm guessing this is an error on the backend.

**Comment by julia-martin** [comment]
Oh whoops, the Refresh button not showing immediate results is because I forgot to implement the Redux reducer for that. I'll work on that now

**Comment by julia-martin** [comment]
Okay I think I've got all the bugs fixed, had to add in the metric name and type from the `metrics` table so in the `editExperiment` controller I changed it to a different query that does the join. And I changed the `analyzeExperiment` controller to return back the updated metrics data for the given experiment

**Comment by seanrichardson95** [comment]
Nice, great job fixing those bugs! Just tried it out and it worked!

**Comment by seanrichardson95** [comment]
There's some logs in the console that need to be cleaned up, but other than that I think we're good. Great job Julia!

**Comment by julia-martin** [comment]
Oh sorry, we can get rid of those in the next pull request

**Pull request merged**
