### PR TITLE
Custom assignment

### PR DESCRIPTION
**Pull request by seanrichardson95**
Wow, this took way longer than I thought, but I finally did it!

DB:
- Added a custom_assignments table with columns (id, user_id, flag_id, status)
- If status is true, then the user will be always on for the designated flag. If false, then off.

Backend:
- Endpoints:
```
// GET “/flags/:id/custom-assignments”
// output
{'2': { user123: false,  user888: false}}

// POST “/flags/:id/custom-assignments” input
{ user8: true, user9: false}
// output
{
    "1": {
        "user8": true,
        "user9": false
    }
}

// DELETE “flags/:id/custom-assignments” input
["userId1", "userId2", ...]
// output
{flag_id: 1, user_ids: ["userId1", "userId2", ...]}

// GET “/custom-assignments”
// output
{
  '1': {
       user123: true,
       user234: false,
       user456: true
      },
  '2': { user123: false,  user888: false},
  '3': {}
}
```
- All the endpoints use the cAssignmentController (custom assignment controller)
- Added a function called `cAssignmentController.setAssignmentsOnEachFlag` that takes the `req.flags` object and puts assignments on it. It's used as middleware for the flags webhook.
- Slightly changed the query made in db/flags/getFlagsForWebhook so it gets the `id` which I use to set the right custom assignments to the right flags

Frontend
- Created redux state and actions for the custom assignments
- Created a button on the `FlagDetailsPage` that shows/hides the custom assignments that are related to that flag
image
image
- Edited the `EditFlagForm` to be able to add and delete custom assignments
  - You can see what the changes will look like immediately, but they aren't sent to the database/API until you hit "submit changes"
  - I had to include a lot of logic here because there were many things that could cause errors when inserting into a database. Like let's say someone added a new assignment, but then decided to delete it. You can't send that deletion, since the new assignment isn't currently in a database. Or what if you delete an assignment, but then add it again, but this time it instead of Always On, it's Always Off.

image

### CODE REVIEW

**Review by julia-martin — COMMENTED** [review]
Wow, that was a lot! I had no idea this feature would be so complicated to implement. Great job getting all of this together and on the coding! The user interaction is really nice as well. The only thing to change maybe is I saw some console log statements, not sure if you meant to keep those or not
console

**Comment by julia-martin** [comment]
Oh just one more thing I forgot to add, at first when I saw the "Always On" button I didn't even realize I could click on it. Maybe you could make it more obvious by adding a border or background or something to make it stick out and not look like static text
dropdown

**Comment by calebrs** [comment]
Yeah, this is great!

**Comment by seanrichardson95** [comment]
Removed the log and changed the CSS of the Select. Let me know what you think.
This is what it looks like for me, but it could look different for y'all. 
image

**Comment by julia-martin** [comment]
It looks better but it's a little too much for me, I'd prefer just border or just background, like one of these (I also added more padding in these examples)
border
dropdown

**Pull request merged**
