### PR TITLE
Experiments data operations

### PR DESCRIPTION
**Pull request by julia-martin**
- First we need the `experiments` table in your SQL file.
- When the user clicks "Create an experiment" or "Stop experiment":
- Inside of `flagsController.editFlag`, it checks if the `is_experiment` field is one of the updated fields. If it is, it calls `createExperiment(id)` or `stopExperiment(id)` depending on if the field is set to true or false.
- Implemented these functions in the `experimentController` file.
- Creating an experiment uses the `PGTable.insertRow()` method to insert a new row into the `experiments` SQL table.
- Stopping an experiment requires the `db/experiments.js` file which contains the UPDATE SQL query.

I've tested it with the UI and checked the SQL table after each operation to confirm they all work. Let me know if you have any comments or questions!

### CODE REVIEW

**Comment by julia-martin** [comment]
Still need to show the newly created experiment ID on the UI. Doing that next

**Comment by julia-martin** [comment]
experiments

**Comment by seanrichardson95** [comment]
Great work!

**Comment by calebrs** [comment]
Looks good to me. I'm okay with a merge.

**Pull request merged**
