### PR TITLE
Flag events

### PR DESCRIPTION
**Pull request by julia-martin**
- Added middleware to POST, PUT and DELETE flags that add an entry to the `flag_events` table
- Added an API route for GET /log that fetches the logs for the Flag Events page
- Created backend controllers for the middleware and GET route
- Added Redux reducer, action creators, state
- Added a function to ApiClient to get the log data
- Created `FlagLogPage` component which displays all the logs in a table 
- Dropdown to filter events by flag name, default is "all"

### CODE REVIEW

**Comment by seanrichardson95** [comment]
Log page looks great! For some reason though the `logsController.logEvent` isn't getting triggered, thus my flag events aren't being saved in the DB.

**Comment by seanrichardson95** [comment]
> Log page looks great! For some reason though the `logsController.logEvent` isn't getting triggered, thus my flag events aren't being saved in the DB.

Actually I think I know why. So I'm currently not hooked up to the Provider, thus `await sendWebhook()` is throwing an error, which gets caught before `next()` is called.

It should look like this.
image

**Comment by seanrichardson95** [comment]
Once you clear those two things up, you're good to merge! Great job!

**Comment by julia-martin** [comment]
Ah good catch, I hadn't tested it with the flag provider down. I've fixed it now

**Pull request merged**
