### PR TITLE
Create CRON job for counting exposures in experiments

### PR DESCRIPTION
**Pull request by julia-martin**
- Installed the `node-cron` library
- Created a file called `refreshExptStatus.js` inside a folder called `cron` inside of the `server` directory
- There are 3 main functions that get called:

1. `getActiveExperiments()` - The CRON job first fetches all active experiments by querying from `experiments WHERE date_ended IS NULL`, and returns the array of id's.
2. `countExposures()` - This takes in the output of the previous function, and queries their `experiments` table (using their query) to count how many users were added to each experiment on the previous day, and which treatment (true or false). It returns the row data with each row corresponding to one experiment-cohort.
3. If this succeeds, we run the next function. I don't have anything for the "else" case here but I'm thinking we should send an email or something letting them know it failed and that they need to run it again.
4. `updateExposures()` - This takes in the output of the previous function, and formats the data into a string which will go in the SQL INSERT statement after "VALUES", then runs the SQL statement.

# Testing
- Make sure your `user_event_data_dump.sql` file has the word `treatment` instead of `variation_id` in lines 68 and 222.
- Make sure you have experiment_id 1 running (date_ended is not null)
- Run the data dump, then do an UPDATE on the `experiments` table to set the timestamp to yesterday (`'2022-03-15'`) since that's the date that the CRON job will filter for.
- Run the script by opening your terminal in the `server` directory, and run `node ./cron/refreshExptStatus.js`. For testing purposes this will only run once, but when we deploy it we'll use the CRON scheduling code that I've included in the comments at the bottom of the file.

# Notes
- I haven't added the part for calculating means for metrics yet, wanted to get this out and reviewed first before I do that.
- I had to make some changes to a few other `db` files to get this to work

# Questions
- As I mentioned in step 3, should we send some kind of notification if there's a failure and the data didn't get updated?
- It doesn't handle the case where we're missing data from days before yesterday (like if it ever fails), since it only queries for yesterday. Should we change this so it counts the cumulative number of users from the experiment start date up to the previous day so that we don't have to worry about missing data?

### CODE REVIEW

**Comment by seanrichardson95** [comment]
Looks great. Just tested it and it worked perfectly! 

In regards to "Should we change this so it counts the cumulative number of users from the experiment start date up to the previous day so that we don't have to worry about missing data?"
- I think we should definitely do that. We'd also have to think about what happens when we do encounter missing data. Maybe just compile a list of the dates that data is missing from and determine whether that day has been collected already. If it has been collected, then we'll run an UPDATE query, if not, then we'll do an INSERT query.

**Comment by julia-martin** [comment]
Sounds good, I'll work on changing the query so that it's cumulative

**Comment by julia-martin** [comment]
Made some changes so that missing data won't be an issue anymore, if anyone wants to take another look and try it out. You can test it by setting some of the rows in the `experiments` table to have different dates (within the last 7 days), so you can then see how it shows up in the `exposures` table

**Comment by seanrichardson95** [comment]
This is what I got from running the CRON job after changing a bunch of dates. Aren't we supposed to have the exposures for each date be it's own row?
image

**Comment by julia-martin** [comment]
hm that's weird, it works fine for me. What dates did you change them to?

**Comment by seanrichardson95** [comment]
> hm that's weird, it works fine for me. What dates did you change them to?

ids 1-20 are 2022-03-08
21-50 are 2022-03-13
51-95 are 2022-03-14
96-100 are 2022-03-15

Here's what was logged 
image

**Comment by julia-martin** [comment]
It looks like maybe you don't have the updates, there's some console logs in there that I don't have on mine. Can you try doing git pull again? Also I've moved all of it over to the `lib` folder so it can be used by the API you suggested

**Comment by seanrichardson95** [comment]
Just got some weird results 
image
The results of logging the query:
```Mar 16 2022 19:39:31 SELECT * FROM experiments WHERE false []
Mar 16 2022 19:39:31 SELECT * FROM exposures WHERE false []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-15' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-15' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'test', 50, '2022-03-15'), (1, 'control', 50, '2022-03-15');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-14' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-14' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'test', 45, '2022-03-14'), (1, 'control', 50, '2022-03-14');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-13' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-13' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'test', 1, '2022-03-13'), (1, 'control', 49, '2022-03-13');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-12' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-12' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'control', 20, '2022-03-12');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-11' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-11' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'control', 20, '2022-03-11');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-10' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-10' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'control', 20, '2022-03-10');
     []
Mar 16 2022 19:39:31 SELECT COUNT(1) FROM exposures WHERE date = $1 [ '2022-03-09' ]
Mar 16 2022 19:39:31 SELECT id FROM experiments WHERE date_ended IS NULL []
Mar 16 2022 19:39:31 SELECT expt_table_query FROM connection []
Mar 16 2022 19:39:31 SELECT * FROM connection; []
Mar 16 2022 19:39:31 
      SELECT experiment_id,
        treatment,
        COUNT(user_id) AS num_users
      FROM (SELECT * FROM experiments) AS expt_table
      WHERE experiment_id IN ($1)
        AND DATE(timestamp) <= $2
      GROUP BY 1, 2;
     [ 1, '2022-03-09' ]
Mar 16 2022 19:39:31 
      INSERT INTO exposures (experiment_id, variant, num_users, date)
      VALUES (1, 'control', 20, '2022-03-09');
     []
```

**Comment by julia-martin** [comment]
That looks to me like it works, it's just logging a lot cause there are a lot of queries and the `dbQuery` function always logs all the queries. 

I've finished updating and adding the API endpoint if you want to check that out

**Comment by seanrichardson95** [comment]
Excellent work! Great job, feel free to merge

**Pull request merged**
